/**
 * Comprehensive list of all Nigerian banks
 * Based on bank logos available in /public/bank_logos/
 * Standardized names for display in the bank transfer drawer
 */
export const ALL_BANKS = [
  // Popular banks
  'GTBank',
  'Access Bank',
  'First Bank',
  'OPay',
  'Kuda',
  'Moniepoint',
  'Zenith Bank',
  'UBA',
  'Palmpay',
  'Providus',
  'WEMA',
  'Sterling Bank',
  'Alat by Wema',

  // Other major banks
  'FCMB',
  'Fidelity Bank',
  'Ecobank',
  'Heritage Bank',
  'Keystone Bank',
  'Union Bank',
  'Unity Bank',
  'Stanbic IBTC',
  'Standard Chartered',
  'Citibank',
  'Globus Bank',
  'Jaiz Bank',
  'Lotus Bank',
  'Suntrust Bank',
  'Titan Trust Bank',
  'Optimus Bank',
  'Parallex Bank',
  'PremiumTrust Bank',
  'Polaris Bank',

  // Fintech & Digital Banks
  'Carbon',
  'Paga',
  'Paycom',
  'VFD',
  'Eyowo',
  'Gomoney',
  'Branch',
  'Tangerine Money',

  // Mobile Money / PSB
  '9mobile',
  'Airtel Smartcash',
  'MTN MoMo',
  'Hope PSB',

  // Microfinance Banks
  'Abbey Mortgage Bank',
  'Above Only MFB',
  'Accion Microfinance Bank',
  'Ampersand Microfinance Bank',
  'Amju Unique MFB',
  'Amegy Microfinance Bank',
  'ASO Savings',
  'Bowen Microfinance Bank',
  'Cashconnect MFB',
  'CEMCS Microfinance Bank',
  'Ekondo Microfinance Bank',
  'Firmus MFB',
  'Gateway Mortgage Bank',
  'IBILE MFB',
  'Infinity MFB',
  'Kredi Money MFB',
  'Living Trust Mortgage Bank',
  'Mint MFB',
  'Parkway ReadyCash',
  'Peace Microfinance Bank',
  'Platinum Mortgage Bank',
  'Quickfund MFB',
  'Rand Merchant Bank',
  'Refuge Mortgage Bank',
  'Rockshield Microfinance Bank',
  'Rubies MFB',
  'Safe Haven MFB',
  'Sage Grey Finance',
  'Shield MFB',
  'Solid Allianze MFB',
  'Solid Rock MFB',
  'Stellas MFB',
  'TCF MFB',
  'Unilag Microfinance Bank',
  'Unical MFB',
  'Uhuru MFB',
  'Waya Microfinance Bank',
] as const
