import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Document, Types } from "mongoose";

@Schema({ timestamps: true })
export class QRKit extends Document {
  // Serial number (unique identifier on physical QR kit, never changes)
  @Prop({ required: true, unique: true, index: true })
  serialNumber: string;

  // Merchant ID (null until activated, then permanently linked)
  @Prop({ type: Types.ObjectId, ref: "User", index: true })
  merchantId?: Types.ObjectId;

  // Activation
  @Prop({ default: "pending", index: true })
  activationStatus: string; // 'pending' | 'activated' | 'deactivated'

  // Payment for activation
  @Prop({ unique: true, sparse: true, index: true })
  paystackReference?: string;

  @Prop()
  paystackAccessCode?: string;

  @Prop({ default: 200000 }) // NGN 2,000 in kobo
  activationAmount: number;

  @Prop({ default: "pending", index: true })
  paymentStatus: string; // 'pending' | 'successful' | 'failed'

  @Prop()
  paidAt?: Date;

  @Prop()
  activatedAt?: Date;

  @Prop()
  firstScannedAt?: Date;

  // Agent assignment (field sales representative)
  @Prop({ type: Types.ObjectId, ref: "Agent", index: true })
  agentId?: Types.ObjectId;

  @Prop()
  assignedToAgentAt?: Date;

  // QR Code (generated by admin, never regenerated)
  @Prop()
  qrCodeSvgUrl?: string; // Cloudinary URL for SVG

  @Prop()
  qrCodeSvgPublicId?: string; // Cloudinary public ID for deletion

  @Prop()
  name?: string;
}

export const QRKitSchema = SchemaFactory.createForClass(QRKit);
export type QRKitDocument = QRKit & Document;

// Indexes
QRKitSchema.index({ serialNumber: 1 });
QRKitSchema.index({ merchantId: 1 });
QRKitSchema.index({ paystackReference: 1 }, { sparse: true });
QRKitSchema.index({ paymentStatus: 1 });
QRKitSchema.index({ activationStatus: 1 });
QRKitSchema.index({ agentId: 1 });
