import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose'
import { Document, Types } from 'mongoose'

export const QR_KIT_LINK_STATUSES = ['linked', 'unlinked'] as const
export type QRKitLinkStatus = (typeof QR_KIT_LINK_STATUSES)[number]

export const QR_KIT_SOURCES = [
  'self-generated',
  'admin-generated',
  'online-order',
] as const
export type QRKitSource = (typeof QR_KIT_SOURCES)[number]

@Schema({ timestamps: true })
export class QRKit extends Document {
  // Serial number (unique identifier on physical QR kit, never changes)
  @Prop({ required: true, unique: true, index: true })
  serialNumber: string

  // Merchant ID (null until activated, then permanently linked)
  @Prop({ type: Types.ObjectId, ref: 'User', index: true })
  merchantId?: Types.ObjectId

  // Activation
  @Prop({ default: 'pending', index: true })
  activationStatus: string // 'pending' | 'activated' | 'deactivated'

  // Payment for activation
  @Prop({ unique: true, sparse: true, index: true })
  paystackReference?: string

  @Prop()
  paystackAccessCode?: string

  @Prop({ default: 300000 }) // NGN 3,000 in kobo
  activationAmount: number

  @Prop({ default: 'pending', index: true })
  paymentStatus: string // 'pending' | 'successful' | 'failed'

  @Prop({ default: false, index: true })
  isDigital: boolean

  // Whether this kit was attached through the physical serial-number flow.
  // A merchant can own a self-generated digital kit while it remains unlinked.
  @Prop({ type: String, enum: QR_KIT_LINK_STATUSES, index: true })
  linkStatus?: QRKitLinkStatus

  // The flow that originally created this QR kit record.
  @Prop({ type: String, enum: QR_KIT_SOURCES, index: true })
  source?: QRKitSource

  // Online orders reserve physical inventory without linking it. The
  // merchant still completes the normal serial-number activation flow later.
  @Prop({ type: Types.ObjectId, ref: 'QROrder', index: true })
  reservedForOrderId?: Types.ObjectId

  @Prop({ type: Types.ObjectId, ref: 'User', index: true })
  reservedForMerchantId?: Types.ObjectId

  @Prop()
  reservedAt?: Date

  @Prop()
  reservationFulfilledAt?: Date

  @Prop()
  paidAt?: Date

  @Prop()
  activatedAt?: Date

  @Prop()
  firstScannedAt?: Date

  // Agent assignment (field sales representative)
  @Prop({ type: Types.ObjectId, ref: 'Agent', index: true })
  agentId?: Types.ObjectId

  @Prop()
  assignedToAgentAt?: Date

  // QR Code (generated by admin, never regenerated)
  @Prop()
  qrCodeSvgUrl?: string // Cloudinary URL for SVG

  @Prop()
  qrCodeSvgPublicId?: string // Cloudinary public ID for deletion

  @Prop()
  name?: string
}

export const QRKitSchema = SchemaFactory.createForClass(QRKit)
export type QRKitDocument = QRKit & Document

// Indexes
// Standard indexes are handled by @Prop annotations.
QRKitSchema.index({
  isDigital: 1,
  activationStatus: 1,
  merchantId: 1,
  agentId: 1,
  reservedForOrderId: 1,
})
